export enum GameEvent {
  SCORE_CHANGED = 'SCORE_CHANGED',
  GAME_STARTED = 'GAME_STARTED',
  GAME_ENDED = 'GAME_ENDED',
  FLIPPED_CARDS_COUNT_CHANGED = 'FLIPPED_CARDS_COUNT_CHANGED',
  TIME_CHANGED = 'TIME_CHANGED',
  GAME_STATUS_CHANGED = 'GAME_STATUS_CHANGED',
}
